source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DYSHelpers_Example', :exclusive => true do
  pod "DYSHelpers", :path => "../"
end

target 'DYSHelpers_Tests', :exclusive => true do
  pod "DYSHelpers", :path => "../"

  
end
