source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DingYusong/DYSPecs.git'

use_frameworks!

target 'DYSHelpers_Example', :exclusive => true do
  pod "DYSHelpers", :path => "../"
end

target 'DYSHelpers_Tests', :exclusive => true do
  pod "DYSHelpers", :path => "../"
  
end
